name: .NET CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  buildConfiguration: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.buildConfiguration }}

      - name: Publish
        run: dotnet publish --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{ github.workspace }}/publish

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Run tests
        run: dotnet test --configuration ${{ env.buildConfiguration }} --no-build --verbosity normal

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying application..."