name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        required: true
        type: string
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ job.reusable-job.outputs.current-time }}
    

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ step.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
