name: Test with Different Feature Flags

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        feature-flag: [true, false]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with feature flag ${{ matrix.feature-flag }}
        run: npm test
        env:
          FEATURE_FLAG: ${{ matrix.feature-flag }}
          CI: true